# Generated by Django 6.0.5 on 2026-05-12 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.CharField(max_length=50, unique=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrega', 'Entrega de Producto'), ('retiro', 'Retiro de Receta'), ('reemplazo', 'Reemplazo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_transito', 'En Transito'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('hora_estimada_entrega', models.TimeField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('firma_confirmacion', models.ImageField(blank=True, null=True, upload_to='movimientos/firmas/')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='motoristas.motorista')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.sucursal')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['numero_despacho'], name='movimiento_numero__af5594_idx'), models.Index(fields=['motorista', 'estado'], name='movimiento_motoris_cb5817_idx'), models.Index(fields=['fecha_programada'], name='movimiento_fecha_p_b3873d_idx')],
            },
        ),
    ]
