# Generated by Django 6.0.5 on 2026-06-09 05:45

import django.db.models.deletion
from django.db import migrations, models


def migrar_sucursales_movimientos(apps, schema_editor):
    Movimiento = apps.get_model('movimientos', 'Movimiento')
    SucursalFlota = apps.get_model('motoristas', 'Sucursal')
    SucursalAntigua = apps.get_model('movimientos', 'Sucursal')

    for movimiento in Movimiento.objects.select_related('sucursal').all():
        sucursal_antigua = movimiento.sucursal
        if sucursal_antigua is None:
            continue

        sucursal_flota, _ = SucursalFlota.objects.get_or_create(
            nombre=sucursal_antigua.nombre,
            defaults={
                'ciudad': sucursal_antigua.ciudad,
                'direccion': sucursal_antigua.direccion,
                'telefono': sucursal_antigua.telefono or '',
                'activo': getattr(sucursal_antigua, 'activa', True),
            },
        )
        Movimiento.objects.filter(pk=movimiento.pk).update(sucursal_id=sucursal_flota.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0003_unify_sucursal_model'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrar_sucursales_movimientos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motoristas.sucursal'),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
