# Generated by Django 6.0.5 on 2026-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_unify_sucursal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_comuna',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='destinatario_telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
