# Generated by Django 6.0.5 on 2026-06-16 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0004_geografia_y_moto_responsable'),
        ('movimientos', '0005_movimiento_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='comentario_incidencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('incidencia', 'Incidencia')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='motoristas.motorista'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to='motoristas.sucursal'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_incidencia',
            field=models.CharField(blank=True, choices=[('direccion_incorrecta', 'Dirección incorrecta'), ('cliente_ausente', 'Cliente ausente'), ('problema_mecanico', 'Problema mecánico'), ('no_entregado', 'No fue posible entregar'), ('otro', 'Otro')], default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['motorista', 'estado'], name='movimiento_motoris_cb5817_idx'),
        ),
    ]
