# Generated by Django 6.0.5 on 2026-07-04 23:42

import django.db.models.deletion
from django.db import migrations, models


def poblar_direccion_origen(apps, schema_editor):
    Movimiento = apps.get_model('movimientos', 'Movimiento')
    for movimiento in Movimiento.objects.select_related('sucursal').all():
        if movimiento.sucursal_id and not movimiento.direccion_origen:
            sucursal = movimiento.sucursal
            partes = [
                p for p in (
                    getattr(sucursal, 'direccion', ''),
                    getattr(sucursal, 'comuna', ''),
                    getattr(sucursal, 'provincia', ''),
                    getattr(sucursal, 'region', ''),
                ) if p
            ]
            movimiento.direccion_origen = ', '.join(partes) if partes else getattr(sucursal, 'direccion', '')
            movimiento.save(update_fields=['direccion_origen'])


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0005_arquitectura_logistica'),
        ('movimientos', '0006_portal_motorista_estado_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='direccion_origen',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='despachos',
                to='motoristas.sucursal',
                verbose_name='Farmacia origen',
            ),
        ),
        migrations.RunPython(poblar_direccion_origen, migrations.RunPython.noop),
    ]
