# Generated by Django 6.0.5 on 2026-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('despachador', 'Despachador'), ('operador', 'Operador'), ('motorista', 'Motorista')], default='motorista', max_length=20),
        ),
    ]
