# Generated by Django 6.0.5 on 2026-07-04 23:42

from django.db import migrations, models


def migrar_roles_despachador(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(rol='despachador').update(rol='supervisor')


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.RunPython(migrar_roles_despachador, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Usuario del sistema', 'verbose_name_plural': 'Usuarios del sistema'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='tipo',
            field=models.CharField(
                choices=[('admin', 'Administración'), ('supervision', 'Supervisión'), ('operacion', 'Operación')],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('administrador', 'Administrador del sistema'),
                    ('supervisor', 'Supervisor / Gerencia'),
                    ('operador', 'Operadora'),
                    ('motorista', 'Motorista'),
                ],
                default='operador',
                max_length=20,
            ),
        ),
    ]
