# Generated by Django 6.0.5 on 2026-05-12 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('tipo_licencia', models.CharField(default='B', max_length=5)),
                ('vigencia_licencia', models.DateField()),
                ('vehiculo_placa', models.CharField(blank=True, max_length=20)),
                ('marca_vehiculo', models.CharField(blank=True, max_length=50)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=50)),
                ('año_vehiculo', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('movimientos_completados', models.IntegerField(default=0)),
                ('calificacion_promedio', models.FloatField(default=5.0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'motorista',
                'ordering': ['-creado_en'],
            },
        ),
    ]
