# Generated by Django 6.0.5 on 2026-06-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0002_add_moto_sucursal'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='motorista',
                    name='año_vehiculo',
                ),
                migrations.RemoveField(
                    model_name='motorista',
                    name='marca_vehiculo',
                ),
                migrations.RemoveField(
                    model_name='motorista',
                    name='modelo_vehiculo',
                ),
                migrations.RemoveField(
                    model_name='motorista',
                    name='vehiculo_placa',
                ),
            ],
        ),
    ]
