# Generated by Django 6.0.5 on 2026-07-04 23:42

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def migrar_encargado_y_asignaciones(apps, schema_editor):
    Sucursal = apps.get_model('motoristas', 'Sucursal')
    Motorista = apps.get_model('motoristas', 'Motorista')
    AsignacionOperativa = apps.get_model('motoristas', 'AsignacionOperativa')

    for sucursal in Sucursal.objects.select_related('encargado__user').all():
        encargado = getattr(sucursal, 'encargado', None)
        if encargado and not sucursal.encargado_nombre:
            user = getattr(encargado, 'user', None)
            if user:
                nombre = f"{user.first_name} {user.last_name}".strip()
                sucursal.encargado_nombre = nombre or user.username
                sucursal.save(update_fields=['encargado_nombre'])

    for motorista in Motorista.objects.all():
        moto_id = getattr(motorista, 'moto_id', None)
        sucursal_id = getattr(motorista, 'sucursal_id', None)
        if sucursal_id:
            AsignacionOperativa.objects.create(
                motorista_id=motorista.id,
                moto_id=moto_id,
                sucursal_id=sucursal_id,
                activa=True,
            )



class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0004_geografia_y_moto_responsable'),
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Farmacia origen', 'verbose_name_plural': 'Farmacias origen'},
        ),
        migrations.AddField(
            model_name='sucursal',
            name='encargado_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='AsignacionOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='motoristas.moto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='motoristas.motorista')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='motoristas.sucursal')),
            ],
            options={
                'verbose_name': 'Asignación operativa',
                'verbose_name_plural': 'Asignaciones operativas',
                'db_table': 'asignacion_operativa',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RunPython(migrar_encargado_y_asignaciones, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='motorista',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='encargado',
        ),
        migrations.AddConstraint(
            model_name='asignacionoperativa',
            constraint=models.UniqueConstraint(
                condition=Q(activa=True),
                fields=('motorista',),
                name='unique_asignacion_activa_por_motorista',
            ),
        ),
    ]
